// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVL5DkQZCsv8ORzTDiVmV4yHLMf1NVQE',
    appId: '1:672403775075:web:25dc53ae222f4b3644e256',
    messagingSenderId: '672403775075',
    projectId: 'levva-app',
    authDomain: 'levva-app.firebaseapp.com',
    databaseURL: 'https://levva-app-default-rtdb.firebaseio.com',
    storageBucket: 'levva-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMb65cALUACn4gEr4Zhrlmu10LuEr1fY',
    appId: '1:672403775075:android:f6f0af5c5476b12444e256',
    messagingSenderId: '672403775075',
    projectId: 'levva-app',
    databaseURL: 'https://levva-app-default-rtdb.firebaseio.com',
    storageBucket: 'levva-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtLrmw65Vw6HtvWrPMrReCpvtDDwGTjs',
    appId: '1:672403775075:ios:e5a37a7b314f3cbb44e256',
    messagingSenderId: '672403775075',
    projectId: 'levva-app',
    databaseURL: 'https://levva-app-default-rtdb.firebaseio.com',
    storageBucket: 'levva-app.firebasestorage.app',
    androidClientId:
        '672403775075-6cvmvcep3upnm1hm48ds7bg8fld2qs2p.apps.googleusercontent.com',
    iosClientId:
        '672403775075-l1evlktuuni6lh14onos9jumpdqljo6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.levva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtLrmw65Vw6HtvWrPMrReCpvtDDwGTjs',
    appId: '1:672403775075:ios:e5a37a7b314f3cbb44e256',
    messagingSenderId: '672403775075',
    projectId: 'levva-app',
    databaseURL: 'https://levva-app-default-rtdb.firebaseio.com',
    storageBucket: 'levva-app.firebasestorage.app',
    androidClientId:
        '672403775075-6cvmvcep3upnm1hm48ds7bg8fld2qs2p.apps.googleusercontent.com',
    iosClientId:
        '672403775075-l1evlktuuni6lh14onos9jumpdqljo6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.levva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbVL5DkQZCsv8ORzTDiVmV4yHLMf1NVQE',
    appId: '1:672403775075:web:b83fbd32884da90944e256',
    messagingSenderId: '672403775075',
    projectId: 'levva-app',
    authDomain: 'levva-app.firebaseapp.com',
    databaseURL: 'https://levva-app-default-rtdb.firebaseio.com',
    storageBucket: 'levva-app.firebasestorage.app',
  );
}
